[package]
name = "ex-bb3-b-redis-pingpong-serde"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"
serde = { version = "*", features = ["derive"] }
serde_bytes = "0.11"